update readme docs
fixes this error
```
~@LOCAL:~$ sqrl run simple.sqrl -s 'Username="josh"' Message
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'sqrl-engine'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jtempelsman/.npm-global/lib/node_modules/sqrl-cli/node_modules/sqrl-cli-functions/lib/index.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```